### 학습목표
 - 다양한 방법으로 ndarray 생성하기

In [1]:
import numpy as np

#### np.array 함수로 생성하기

In [2]:
x= np.array([1,2,3,4])
print(x)

y=np.array([[2,3,4],[1,2,5]])
print(y)

print(type(y))

[1 2 3 4]
[[2 3 4]
 [1 2 5]]
<class 'numpy.ndarray'>


#### np.arange 함수로 생성하기

In [3]:
#python에서 range함수와 같음
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [6]:
np.arange(5,101,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

#### np.ones, np.zeros로 생성하기

In [7]:
#2행 3열에 모든 원소가 1인 행렬

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [9]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### np.empty, np.full로 생성하기

In [10]:
np.empty((3,4)) #랜덤?

array([[6.64476605e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.16324355e+165, 4.89171506e-033,
        4.66376326e-033],
       [1.11644505e-046, 1.31377835e-071, 1.54754427e-075,
        2.23037091e+180]])

In [11]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### np.eye로 생성하기
 - 단위 행렬 생성

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### np.linspace로 생성하기

In [13]:
np.linspace(1, 10, 3)
#범위 내에 간격 동일하게 3칸

array([ 1. ,  5.5, 10. ])

In [14]:
np.linspace(1,21,5)

array([ 1.,  6., 11., 16., 21.])

#### reshape 함수 활용
 - ndarray의 형태, 차원을 바꾸기 위해 사용

In [15]:
x = np.arange(1,16)
print(x)
x.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


(15,)

In [16]:
x.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
x.reshape(1,3,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [18]:
x.reshape(3,1,5)

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]]])