### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [2]:
np.random.rand(2,3)

array([[0.9198888 , 0.9588151 , 0.35893309],
       [0.19917775, 0.28615648, 0.94509171]])

In [3]:
np.random.rand(2)

array([0.40465603, 0.44003886])

In [4]:
np.random.rand(4,5,3)

array([[[0.21847327, 0.71867358, 0.26804879],
        [0.56726773, 0.84035412, 0.90344251],
        [0.0961871 , 0.97847635, 0.79112406],
        [0.68717646, 0.19510431, 0.03577478],
        [0.74991181, 0.0193598 , 0.80011282]],

       [[0.05027104, 0.77590083, 0.0016522 ],
        [0.88175873, 0.62198607, 0.18901127],
        [0.12781848, 0.21070653, 0.92029594],
        [0.0920885 , 0.24815313, 0.8144465 ],
        [0.27400978, 0.90896416, 0.24069436]],

       [[0.01678294, 0.04646677, 0.93827023],
        [0.95140206, 0.48690209, 0.79125622],
        [0.57001973, 0.08679072, 0.38691311],
        [0.57266237, 0.37846227, 0.21340309],
        [0.88170674, 0.88076593, 0.57329862]],

       [[0.10348854, 0.36695875, 0.86753801],
        [0.25703181, 0.97221617, 0.18071359],
        [0.79575135, 0.83957381, 0.86755599],
        [0.92914118, 0.82645856, 0.30966227],
        [0.34216101, 0.35434512, 0.43769883]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [5]:
np.random.randn(2,3)

array([[ 1.96729969e-01,  3.16621226e-01,  1.35160787e-01],
       [-1.47791292e+00,  4.08837443e-01,  1.45877003e-03]])

In [6]:
np.random.randn(3)

array([-0.54483269,  1.32219175,  1.24857486])

In [7]:
np.random.randn(2,3,4)

array([[[ 0.19522332,  1.3091543 ,  1.77925619,  1.6297403 ],
        [-1.90945468,  0.31534963,  0.8764202 ,  0.35153109],
        [-1.30389003,  1.22305293,  0.12053059, -1.65173819]],

       [[-1.06588167, -1.54983035, -1.78355172, -1.4292434 ],
        [ 1.40110883, -0.75161317, -0.52006993, -0.86451308],
        [-0.45024154,  0.98087562,  0.03577365,  1.35622933]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [8]:
np.random.randint(1,100,size=(3,5))
#1부터 100까지 정수를 랜덤하게  3행5열로

array([[68, 86, 48, 83, 66],
       [69, 32, 30, 45, 40],
       [ 7, 42, 77, 56, 91]])

In [9]:
np.random.randint(1,100, size=(5,))

array([15, 24, 60,  9,  2])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [10]:
np.random.seed(100)
#실험번호라고 생각하면 됨
#seed 실행후 그 다음 값은 고정이 됨

In [11]:
np.random.randn(3,4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

In [12]:
np.random.randn(3,4)

array([[-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [13]:
np.random.choice(100, size=(3, 4))

array([[39, 38, 44, 18],
       [64, 56, 34, 53],
       [74, 17, 72, 13]])

In [14]:
x= np.array([1,2,3,1.5,2.6,4.9])
np.random.choice(x, size=(2,2))

array([[3. , 2. ],
       [4.9, 2.6]])

In [15]:
np.random.choice(x,size=(2,2),replace=False)
#사용했던거는 다시 못 쓰게 : replace=F

array([[4.9, 2.6],
       [2. , 1.5]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [16]:
np.random.uniform(1.0,3.0, size=(4,5))

array([[2.67226363, 1.15078982, 1.02280158, 1.09684114, 1.71424542],
       [2.33138675, 1.02277922, 1.21583553, 2.8020262 , 2.58975752],
       [2.62292196, 2.28055611, 2.24955902, 1.29101502, 2.1404318 ],
       [1.130225  , 1.62682514, 1.43413153, 2.05390078, 1.85421676]])

In [17]:
np.random.normal(size=(3,4))

array([[ 0.79067165,  0.68000189,  0.71660582,  0.47770485],
       [-0.66623993,  0.08448008, -0.33876049,  0.70592118],
       [-1.6017614 ,  0.39324807, -0.60165768,  1.83797752]])

In [18]:
np.random.randn(3,4)

array([[-0.01994237,  0.4212484 , -0.19530941, -0.21627238],
       [-0.68825288,  0.00473325,  0.42469019, -0.20090269],
       [-0.75783351, -2.26909897, -0.9565702 ,  0.19481524]])