## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [2]:
x = np.arange(15).reshape(3,5)
y = np.random.rand(15).reshape(3,5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.44676799 0.92973139 0.94374317 0.41004244 0.9106638 ]
 [0.28417267 0.07666448 0.84674275 0.58349354 0.4100867 ]
 [0.2342443  0.44849761 0.19679924 0.87910171 0.94998019]]


#### 연산 함수
 - add, substract, multiply, divide

In [3]:
np.add(x,y)  ##shape이 같아야 연산 가능

array([[ 0.44676799,  1.92973139,  2.94374317,  3.41004244,  4.9106638 ],
       [ 5.28417267,  6.07666448,  7.84674275,  8.58349354,  9.4100867 ],
       [10.2342443 , 11.44849761, 12.19679924, 13.87910171, 14.94998019]])

In [4]:
np.subtract(x,y)

array([[-0.44676799,  0.07026861,  1.05625683,  2.58995756,  3.0893362 ],
       [ 4.71582733,  5.92333552,  6.15325725,  7.41650646,  8.5899133 ],
       [ 9.7657557 , 10.55150239, 11.80320076, 12.12089829, 13.05001981]])

In [5]:
x+y

array([[ 0.44676799,  1.92973139,  2.94374317,  3.41004244,  4.9106638 ],
       [ 5.28417267,  6.07666448,  7.84674275,  8.58349354,  9.4100867 ],
       [10.2342443 , 11.44849761, 12.19679924, 13.87910171, 14.94998019]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [6]:
print(y)

[[0.44676799 0.92973139 0.94374317 0.41004244 0.9106638 ]
 [0.28417267 0.07666448 0.84674275 0.58349354 0.4100867 ]
 [0.2342443  0.44849761 0.19679924 0.87910171 0.94998019]]


In [7]:
np.mean(y)

0.5700487995916242

In [8]:
np.max(y)

0.9499801917039696

In [9]:
np.argmax(y)
#flatten 한 상태로 index를 계산

14

In [10]:
np.var(y), np.median(y), np.std(y)

(0.09066902698449361, 0.44849761284809153, 0.30111298043175355)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [11]:
np.sum(y)

8.550731993874363

In [12]:
np.cumsum(y)
#각 원소의 누적합

array([0.44676799, 1.37649938, 2.32024256, 2.730285  , 3.6409488 ,
       3.92512147, 4.00178595, 4.8485287 , 5.43202225, 5.84210894,
       6.07635324, 6.52485086, 6.72165009, 7.6007518 , 8.55073199])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [13]:
np.std(np.arange(1, 5)) 

1.118033988749895

In [14]:
z=np.random.randn(10)
print(z)

[ 2.78210635  0.03574276 -0.63028271  0.4184142   0.05609694  0.2534424
 -1.44377165 -0.51259246  0.97440474 -0.39370431]


In [15]:
np.any(z>0)
#조건이 하나라도 맞으면 True

True

In [16]:
np.all(z>0)
#조건이 모두 맞으면 True

False

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [17]:
z=np.random.randn(10)
print(z)

[-2.0527312  -0.15258594 -1.22858045  0.28953464 -1.22708256 -0.5735493
  0.23413131 -0.34476443 -0.57191849  0.19702966]


In [18]:
np.where(z>0,1,0)

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 1])

In [19]:
np.where(z>0,z,0)

array([0.        , 0.        , 0.        , 0.28953464, 0.        ,
       0.        , 0.23413131, 0.        , 0.        , 0.19702966])