## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [1]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [2]:
x = np.random.rand(3, 3, 3)
print(x)

np.matmul(x, np.linalg.inv(x))
x @ np.linalg.inv(x)

[[[0.86048097 0.25053075 0.56925858]
  [0.1252675  0.25325154 0.3566675 ]
  [0.46151312 0.51201971 0.61490602]]

 [[0.98090288 0.17041297 0.44455943]
  [0.22662679 0.13538481 0.68348003]
  [0.51367768 0.12080435 0.13625642]]

 [[0.11234039 0.7873887  0.16838   ]
  [0.18421607 0.50968429 0.907876  ]
  [0.11423651 0.85084466 0.54695214]]]


array([[[ 1.00000000e+00,  8.88178420e-16,  0.00000000e+00],
        [ 1.11022302e-16,  1.00000000e+00,  0.00000000e+00],
        [ 2.22044605e-16,  8.88178420e-16,  1.00000000e+00]],

       [[ 1.00000000e+00, -1.11022302e-16, -2.22044605e-16],
        [ 2.22044605e-16,  1.00000000e+00,  0.00000000e+00],
        [ 1.94289029e-16, -1.11022302e-16,  1.00000000e+00]],

       [[ 1.00000000e+00,  1.31838984e-16,  4.99600361e-16],
        [ 0.00000000e+00,  1.00000000e+00,  8.88178420e-16],
        [ 0.00000000e+00,  1.38777878e-16,  1.00000000e+00]]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [3]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

np.allclose(A@x, B)

[18.  7.]


True